name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Build docs site
        working-directory: ./docs-site
        env:
          NEXT_PUBLIC_BASE_PATH: /devbar/docs
          NEXT_PUBLIC_DEMO_URL: https://${{ github.repository_owner }}.github.io/devbar
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          pnpm install
          rm -rf .next out
          echo "Node version: $(node --version)"
          echo "pnpm version: $(pnpm --version)"
          pnpm build

      - name: Build demo app
        working-directory: ./demo-app
        env:
          NEXT_PUBLIC_BASE_PATH: /devbar
          NEXT_PUBLIC_DOCS_URL: https://${{ github.repository_owner }}.github.io/devbar/docs
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          pnpm install
          rm -rf .next out
          echo "Node version: $(node --version)"
          echo "pnpm version: $(pnpm --version)"
          ls -la app/
          pnpm build

      - name: Combine outputs
        run: |
          mkdir -p ./public-deploy
          cp -r ./demo-app/out/* ./public-deploy/
          mkdir -p ./public-deploy/docs
          cp -r ./docs-site/out/* ./public-deploy/docs/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public-deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4